### ISSUE TITLE
About the downloading errors  by using azcopy

### ISSUE THREAD

**Issue by Glupayy** [microsoft/TAP#6]
Hi, when I used azcopy command to download the data, the connection always reset by the remote host in the middle. I have tried this for two weeks but the error still remain...
So, may I know any other alternative ways downloading the data? Thanks a lot!

**Comment by zyang-ur** [comment]
Hi @Glupapa ,

So the problem is that the downloading will stopped in the middle? In this case, azcopy should still save the part downloaded, and you could resume on downloading the remaining part? Is the problem for all links or a specific folder?

Another option is to try an older version of the azcopy, e.g., v8/7 instead of v10.

**Comment by Glupayy** [comment]
Thanks!
I tried azcopy v8 and the problem solved.
